
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.coobird.thumbnailator.Thumbnails;
import net.proteanit.sql.DbUtils;


/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class EmployeeDetails extends javax.swing.JFrame {
     /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
        
        //initializes conn object MySqlConnect's connectDb()
        conn = MySqlConnect.connectDB();
        rbtTemp.setVisible(false);
        String sql = "SELECT * FROM employeeinfo";
        updateTableData(sql);
        //jTable1.setRowHeight(0,10);
        
        txtSearch.getDocument().addDocumentListener(new DocumentListener(){

            @Override
            public void insertUpdate(DocumentEvent e) {
                searchFilter();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                searchFilter();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {}
            
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnGroupGender = new javax.swing.ButtonGroup();
                jDateChooser1 = new com.toedter.calendar.JDateChooser();
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                txtEmpID = new javax.swing.JTextField();
                txtName = new javax.swing.JTextField();
                txtAge = new javax.swing.JTextField();
                txtContactNo = new javax.swing.JTextField();
                cmbBloodGroup = new javax.swing.JComboBox();
                rbtButtonMale = new javax.swing.JRadioButton();
                rbtButtonFemale = new javax.swing.JRadioButton();
                cmbQualification = new javax.swing.JComboBox();
                doj = new com.toedter.calendar.JDateChooser();
                lblAdress = new javax.swing.JLabel();
                lblImagePath = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtAreaAddress = new javax.swing.JTextArea();
                btnUploadImage = new javax.swing.JButton();
                txtImagePath = new javax.swing.JTextField();
                jDesktopPane1 = new javax.swing.JDesktopPane();
                lblImage = new javax.swing.JLabel();
                rbtTemp = new javax.swing.JRadioButton();
                jPanel4 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                btnNew = new javax.swing.JButton();
                btnSave = new javax.swing.JButton();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                btnClear = new javax.swing.JButton();
                jLabel9 = new javax.swing.JLabel();
                txtSearch = new javax.swing.JTextField();
                btnPrint = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setForeground(new java.awt.Color(255, 255, 255));

                jPanel2.setBackground(new java.awt.Color(255, 255, 255));

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));
                jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel1.setText("Employee ID");

                jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel2.setText("Name");

                jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel3.setText("Gender");

                jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel4.setText("Age");

                jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel5.setText("BloodGroup");

                jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel6.setText("ContactNo");

                jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel7.setText("Qualification");

                jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
                jLabel8.setText("DOJ");

                txtEmpID.setNextFocusableComponent(txtName);

                txtName.setNextFocusableComponent(rbtButtonMale);

                txtAge.setNextFocusableComponent(cmbBloodGroup);

                txtContactNo.setNextFocusableComponent(cmbQualification);

                cmbBloodGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+B-", "AB+", "AB-", "O+", "O-" }));
                cmbBloodGroup.setSelectedIndex(-1);
                cmbBloodGroup.setNextFocusableComponent(txtContactNo);

                rbtButtonMale.setBackground(new java.awt.Color(255, 255, 255));
                btnGroupGender.add(rbtButtonMale);
                rbtButtonMale.setText("Male");
                rbtButtonMale.setNextFocusableComponent(rbtButtonFemale);
                rbtButtonMale.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbtButtonMaleActionPerformed(evt);
                        }
                });

                rbtButtonFemale.setBackground(new java.awt.Color(255, 255, 255));
                btnGroupGender.add(rbtButtonFemale);
                rbtButtonFemale.setText("Female");
                rbtButtonFemale.setNextFocusableComponent(txtAge);
                rbtButtonFemale.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbtButtonFemaleActionPerformed(evt);
                        }
                });

                cmbQualification.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BTECH", "BCOM ", "DEGREE", "CS", " " }));
                cmbQualification.setSelectedIndex(-1);
                cmbQualification.setNextFocusableComponent(doj);

                doj.setNextFocusableComponent(txtAreaAddress);

                lblAdress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblAdress.setText("Address");

                lblImagePath.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
                lblImagePath.setText("Image Path");

                txtAreaAddress.setColumns(20);
                txtAreaAddress.setRows(5);
                txtAreaAddress.setNextFocusableComponent(btnUploadImage);
                jScrollPane1.setViewportView(txtAreaAddress);

                btnUploadImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image upload.png"))); // NOI18N
                btnUploadImage.setText("Upload Image");
                btnUploadImage.setNextFocusableComponent(txtImagePath);
                btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUploadImageActionPerformed(evt);
                        }
                });

                txtImagePath.setNextFocusableComponent(txtSearch);

                jDesktopPane1.setBackground(new java.awt.Color(102, 102, 102));

                lblImage.setBackground(new java.awt.Color(255, 255, 255));
                lblImage.setForeground(new java.awt.Color(255, 255, 255));
                lblImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

                javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
                jDesktopPane1.setLayout(jDesktopPane1Layout);
                jDesktopPane1Layout.setHorizontalGroup(
                        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jDesktopPane1Layout.setVerticalGroup(
                        jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jDesktopPane1.setLayer(lblImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

                btnGroupGender.add(rbtTemp);
                rbtTemp.setText("temp");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(doj, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                                        .addComponent(cmbQualification, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(lblImagePath))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel3))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(rbtButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(rbtButtonFemale)
                                                                .addGap(3, 3, 3)
                                                                .addComponent(rbtTemp))
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtEmpID)
                                                                        .addComponent(txtName)
                                                                        .addComponent(txtAge)
                                                                        .addComponent(txtContactNo)
                                                                        .addComponent(cmbBloodGroup, 0, 150, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblAdress)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnUploadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtImagePath)
                                        .addComponent(jScrollPane1))
                                .addGap(18, 18, 18)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(19, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jDesktopPane1)
                                                .addGap(38, 38, 38))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lblAdress))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(rbtButtonMale)
                                                                        .addComponent(rbtButtonFemale)
                                                                        .addComponent(rbtTemp))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(cmbBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(cmbQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(btnUploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel7))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(lblImagePath)
                                                                .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(doj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );

                jPanel2.add(jPanel3);

                jPanel4.setBackground(new java.awt.Color(255, 255, 255));

                jPanel5.setBackground(new java.awt.Color(255, 255, 255));

                btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new-icon.png"))); // NOI18N
                btnNew.setText("New");
                btnNew.setNextFocusableComponent(btnSave);
                btnNew.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNewActionPerformed(evt);
                        }
                });

                btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save-icon.png"))); // NOI18N
                btnSave.setText("Save");
                btnSave.setNextFocusableComponent(btnUpdate);
                btnSave.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSaveActionPerformed(evt);
                        }
                });

                btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
                btnUpdate.setText("Update");
                btnUpdate.setNextFocusableComponent(btnDelete);
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });

                btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
                btnDelete.setText("Delete");
                btnDelete.setNextFocusableComponent(btnClear);
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
                btnClear.setText("Clear");
                btnClear.setNextFocusableComponent(jTable1);
                btnClear.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnClearActionPerformed(evt);
                        }
                });

                jLabel9.setText("SEARCH");

                txtSearch.setNextFocusableComponent(btnNew);
                txtSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtSearchActionPerformed(evt);
                        }
                });

                btnPrint.setText("print");
                btnPrint.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPrintActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel5Layout.setVerticalGroup(
                        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave)
                                        .addComponent(btnNew)
                                        .addComponent(btnUpdate)
                                        .addComponent(btnDelete)
                                        .addComponent(btnClear)
                                        .addComponent(jLabel9)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPrint))
                                .addContainerGap())
                );

                jPanel4.add(jPanel5);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 852, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jTable1MouseClicked(evt);
                        }
                });
                jScrollPane2.setViewportView(jTable1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void rbtButtonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtButtonMaleActionPerformed
        // TODO add your handling code here:
        gender="Male";
        
    }//GEN-LAST:event_rbtButtonMaleActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if(txtEmpID.getText().equals("")){
            JOptionPane.showMessageDialog(null, "please select a record to delete ");
        }
        else{
            int btn = JOptionPane.showConfirmDialog(null, "Do you wanna really delete the record  ?", "DELETE", JOptionPane.YES_NO_OPTION);
            System.out.println(btn + "" +JOptionPane.YES_OPTION);
            if(btn == JOptionPane.YES_OPTION){
                try {
                    String sql = "DELETE FROM employeeinfo WHERE empid = ?";
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setString(1,txtEmpID.getText());
                    preparedStatement.execute();
                    JOptionPane.showMessageDialog(null,"Record Delete Successfully:");
                    clearField();
                    String sqlQ = "SELECT * FROM employeeinfo";
                    updateTableData(sqlQ);
                } catch (Exception e) 
                {
                      JOptionPane.showMessageDialog(null,"Delte issue  : "+ e.getMessage());
                }
                finally{
                    try {
                        preparedStatement.close();
                    } catch (Exception e) {
                          JOptionPane.showMessageDialog(null,"error while closing the statement:"+ e.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearField();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "UPDATE employeeinfo SET empname=?,gender=?,age=?,bloodgroup=?,contactinfo=?,qualification=?,doj=?,address=?,empimage=? WHERE empid = ?";
            preparedStatement = conn.prepareStatement(sql);

            preparedStatement.setString(1, txtName.getText());
            preparedStatement.setString(2, gender);
            preparedStatement.setString(3,txtAge.getText());
            preparedStatement.setString(4, cmbBloodGroup.getSelectedItem().toString());
            preparedStatement.setString(5, txtContactNo.getText());
            preparedStatement.setString(6, cmbQualification.getSelectedItem().toString());

            SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
            String strDate = sdf.format(doj.getDate());

            preparedStatement.setString(7, strDate);
            preparedStatement.setString(8, txtAreaAddress.getText());
            preparedStatement.setBytes(9, byteImage);
            preparedStatement.setInt(10, Integer.parseInt(txtEmpID.getText()));
            preparedStatement.execute();         
            JOptionPane.showMessageDialog(null,"Record inserted successfull");
            
              String sqlQ = "SELECT * FROM employeeinfo";
            updateTableData(sqlQ);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"issue:"+ e);
 
        }
        String sql = "SELECT * FROM employeeinfo";
        updateTableData(sql);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File sourcePath = fileChooser.getSelectedFile();
        if(sourcePath!=null){
             filePath = sourcePath.getAbsolutePath();
        txtImagePath.setText(filePath);
            try{
                File image= new File(filePath);
                BufferedImage thumbnail = Thumbnails.of(image).size(180, 220).asBufferedImage();
                
                
                ByteArrayOutputStream os= new ByteArrayOutputStream();
                ImageIO.write(thumbnail, "jpg", os);
                
                byteImage = os.toByteArray();
                
                
                
               // byteImage= Files.readAllBytes(sourcePath.toPath());
                
                viewImage = new ImageIcon(thumbnail);
                lblImage.setIcon(viewImage);
                
            }
            catch(Exception e){
              JOptionPane.showMessageDialog(null,"Connection unsuccessful" ,"Employee",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void rbtButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtButtonFemaleActionPerformed
        // TODO add your handling code here:
        gender="Female";
    }//GEN-LAST:event_rbtButtonFemaleActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO employeeinfo(empname, gender, age, bloodgroup, contactinfo, qualification, doj, address, empimage) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            preparedStatement = conn.prepareStatement(sql);

            preparedStatement.setString(1, txtName.getText());
            preparedStatement.setString(2, gender);
            preparedStatement.setString(3,txtAge.getText());
            preparedStatement.setString(4, cmbBloodGroup.getSelectedItem().toString());
            preparedStatement.setString(5, txtContactNo.getText());
            preparedStatement.setString(6, cmbQualification.getSelectedItem().toString());

            SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
            String strDate = sdf.format(doj.getDate());

            preparedStatement.setString(7, strDate);
            preparedStatement.setString(8, txtAreaAddress.getText());
            preparedStatement.setBytes(9, byteImage);
           // preparedStatement.setInt(10, Integer.parseInt(txtEmpID.getText()));
            
           
            preparedStatement.execute();         
            JOptionPane.showMessageDialog(null,"Record inserted successfull");
 
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"issue:Save`"+ e);
 
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
       
        clearField();
    }//GEN-LAST:event_btnNewActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        String selectedEmpId = jTable1.getModel().getValueAt(selectedRow, 0).toString();
        System.out.println(jTable1.getModel().getValueAt(selectedRow, jTable1.getSelectedColumn()).toString());
        try {
            String sql = "SELECT * FROM employeeinfo WHERE empid = "+selectedEmpId;
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
                  //  `empid`, `empname`, `gender`, `age`, `bloodgroup`, `contactinfo`, `qualification`, `doj`, `address`, `empimage`
            if(rs.next()){
                txtEmpID.setText(rs.getString("empid"));
                txtName.setText(rs.getString("empname"));
                txtAreaAddress.setText(rs.getString("address"));
                txtAge.setText(rs.getString("age"));
                txtContactNo.setText(rs.getString("contactinfo"));
                String genderSelected = rs.getString("gender");
                if("Male".equals(genderSelected)){
                    rbtButtonMale.setSelected(true);
                       gender = "Male";
                }
                else if("Female".equals(genderSelected)){
                     rbtButtonFemale.setSelected(true);
                        gender = "Female";
                }
                cmbQualification.setSelectedItem(rs.getString("qualification"));
                cmbBloodGroup.setSelectedItem(rs.getString("bloodgroup"));
                
                String dateValue = rs.getString("doj");
                Date date= new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                doj.setDate(date);
                byte[] selectdedImagedata = rs.getBytes("empimage");
                /*
                    saving to my class variable  so that while updating if the image is not change then too it will take the  old image 
                */
                byteImage =  selectdedImagedata;
                /************************************************************************************************************************************
                 **********************************SPECIAL LINES OF CODE ****************************************************************************
                 * ********************************************************************************************************************************/
          
                BufferedImage img = Thumbnails.of(ImageIO.read(new ByteArrayInputStream(selectdedImagedata))).size(180,200).asBufferedImage();
                ImageIcon i = new ImageIcon(img);
                //ImageIcon i = new ImageIcon(selectedImageData);
                /*if you remove above lines of comment then please add comment to the above two lines of code*/
                 
                
                /**********************************************************************************************************************************
                 * **********************************************SPECIAL LINES OF CODE ***********************************************************
                 * ******************************************************************************************************************************/
                lblImage.setIcon(i);
            }
                    
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Employee List Report Print");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Some issue in printing : " + e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed
    private void searchFilter(){
        key = txtSearch.getText();
        String updateTableQuery;
        if(!key.equals("")){
            updateTableQuery = "SELECT * FROM employeeinfo WHERE empname like '%" + key + "%'";
            
        }
        else
            updateTableQuery = "SELECT * FROM employeeinfo";
        updateTableData(updateTableQuery);
            
    }
    private void updateTableData(String sql){
        try {
          //  String sql = "SELECT * FROM employeeinfo";
            preparedStatement = conn.prepareStatement(sql);
            rs =  preparedStatement.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //this class is (DbUtils)created by company called Appache 
            //appache wo company hai jiska server ham use kr rahe the database ko connect krne ke liye
            //DbUtils is use for convert the result set into XML of TABLE MODel 
            //this resultSetToTablemodel automatically create the object of the TableModel
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"issue " +e);
        }
        finally{
            try{
                rs.close();
                preparedStatement.close();
            }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Problem in closing rs or preparedStatement" +e);
     
            }
        }
    }
    private void clearField(){
        txtAge.setText("");
        txtAreaAddress.setText("");
        txtContactNo.setText("");
        txtEmpID.setText("");
        txtImagePath.setText("");
        txtName.setText("");
        cmbBloodGroup.setSelectedIndex(-1);
        cmbQualification.setSelectedIndex(-1);
        doj.setDate(null);
        gender=null;
        lblImage.setIcon(null);
        rbtTemp.setSelected(true);
        
//        clearField();
//        updateTableData();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnClear;
        private javax.swing.JButton btnDelete;
        private javax.swing.ButtonGroup btnGroupGender;
        private javax.swing.JButton btnNew;
        private javax.swing.JButton btnPrint;
        private javax.swing.JButton btnSave;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JButton btnUploadImage;
        private javax.swing.JComboBox cmbBloodGroup;
        private javax.swing.JComboBox cmbQualification;
        private com.toedter.calendar.JDateChooser doj;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private javax.swing.JDesktopPane jDesktopPane1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel lblAdress;
        private javax.swing.JLabel lblImage;
        private javax.swing.JLabel lblImagePath;
        private javax.swing.JRadioButton rbtButtonFemale;
        private javax.swing.JRadioButton rbtButtonMale;
        private javax.swing.JRadioButton rbtTemp;
        private javax.swing.JTextField txtAge;
        private javax.swing.JTextArea txtAreaAddress;
        private javax.swing.JTextField txtContactNo;
        private javax.swing.JTextField txtEmpID;
        private javax.swing.JTextField txtImagePath;
        private javax.swing.JTextField txtName;
        private javax.swing.JTextField txtSearch;
        // End of variables declaration//GEN-END:variables
    private ImageIcon viewImage=null;
    private String filePath=null;
    private String gender=null;
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs= null;
    private byte[] byteImage;
    private String key = "";
}